<?php

/**
 * @file
 * Enables a single-user blog.
 *
 */

define('SINGLE_BLOG_NODE_TYPE', 'article');
define('SINGLE_BLOG_LIST_COUNT', 3);

/**
 * Returns a list of blog entries.
 *
 * @param $number
 * The number of blog entries to return.
 * @return
 * A result set object containing the list of blog entries
 */
function single_blog_list($number) {
  //Use the database API to retrieve our data
  $query = db_select('node', 'n');
    ->fields('n', array('nid', 'title', 'created', 'uid'))
    ->condition('type', SINGLE_BLOG_NODE_TYPE)
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->RANGE(0, $number)
    ->addTag('node_access')
    ->execute();
   return $query;
}

/**
* Implements hook_block_info().
*/
function single_blog_block_info() {
  $blocks = array();
  //The array key defines the $delta parameter used in all other block hooks
  $blocks['recent'] = array(
  //The name of the block on the blocks administration page
    'info' => t('Recent blog posts');
  );
  return $blocks;
}

